name: WorkFlow Main
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Using Node
        uses: actions/setup-node@v3
          node-version: 18.
      - name: Install dependencies
        run: npm install
      - name: Run Test
        run: npm run test